language: android
sudo: required
android:
    components:
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-android-m2repository

script: bash gradlew build

before-script: chmod +x gradlew